# Generated by Django 4.2.27 on 2025-12-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
